Added --permissive option.

diff --git a/scripts/read_binary_api b/scripts/read_binary_api
--- a/scripts/read_binary_api
+++ b/scripts/read_binary_api
@@ -1,9 +1,70 @@
 #!/bin/sh
 
+# The MIT License (MIT)
+# 
+# Copyright (c) 2018 Yury Gribov
+# 
+# Use of this source code is governed by The MIT License (MIT)
+# that can be found in the LICENSE.txt file.
+
 # Reads binary APIs from a list of shlibs.
 # TODO: implement this in a saner way
 
 set -eu
+
+print_help_and_exit() {
+  cat <<EOF
+Usage: $(basename $0) [OPT]... FILE...
+Prints symbols exported from FILE.
+
+Options:
+  -x              Enable shell tracing (for debug).
+  -h, --help      Print this help and exit.
+  -v, --verbose   Print diagnostic info (can use more than once for more details).
+  --permissive    Ignore common dummy symbols (_edata, __bss_start, etc.).
+EOF
+  exit 1
+
+}
+
+ARGS=$(getopt -o 'hkxv' --long 'help,verbose,permissive' -n $(basename $0) -- "$@")
+eval set -- "$ARGS"
+
+V=0
+PERM=
+while true; do
+  case "$1" in
+    -x)
+      set -x
+      shift
+      ;;
+    -h | --help)
+      print_help_and_exit
+      ;;
+    -v | --verbose)
+      V=$((V + 1))
+      shift
+      ;;
+    --permissive)
+      PERM=1
+      shift
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*)
+      error "unknown option: $1"
+      ;;
+    *)
+      error 'internal error'
+      ;;
+  esac
+done
+
+if [ $# -eq 0 ]; then
+  print_help_and_exit
+fi
 
 # Note that we skip symbols which use custom versions (marked with single @)
 # as these most probly come from old unsupported interfaces.
@@ -15,5 +76,6 @@ for l in "$@"; do
     | sed 's/@@.*//' \
     | grep -v '^$' \
     | grep -v '@' \
+    | (if test -n "$PERM"; then cat; else grep -v '^\(__bss_start\|_edata\|_init\|_fini\|_etext\|__etext\|_end\)$'; fi) \
     | sort -u
 done | sort -u
